import fs from "fs";
import resolveConfig from "tailwindcss/resolveConfig.js";
import tailwindConfig from "../tailwind.config.js";
import { execSync } from "child_process";

const fullConfig = resolveConfig(tailwindConfig);
const pathname = "./src/shared/ui/theme/_generated.ts";

const fullConfigString =
  `// This file is generated by generateTheme.js\n` +
  `const theme = ${JSON.stringify(fullConfig.theme, null, 2)}\n\n` +
  `export default theme`;
fs.writeFileSync(pathname, fullConfigString);
execSync(`npx prettier --write ${pathname}`);

export default fullConfig;
